### ISSUE TITLE
短信删除速度慢

### ISSUE THREAD

**Issue by pz66** [davidche1116/Sms#1]
功能很好用，就是删除速度很慢，这个希望可以优化下，非常感谢

**Comment by davidche1116** [comment]
@pz66  说一下具体场景，手机型号、删除短信数量。我这边小米、魅族、VIVO测试删除一条短信都很快，1万条也几秒钟。

**Comment by pz66** [comment]
真我GTneo6se， 安卓14，coloros 14，当时过滤出来删除，大概一万多条验证码短信，删除了5分钟都一直在转圈，重新打开软件后发现还剩几千条，又重新删，又消耗了比较长的时间，也删除了几分钟。
已经删完了，我现在没有那么多短信可以测试了

**Comment by pz66** [comment]
真我GTneo6se， 安卓14，coloros 14，当时过滤出来删除，大概一万多条验证码短信，删除了5分钟都一直在转圈，重新打开软件后发现还剩几千条，又重新删，又消耗了比较长的时间，也删除了几分钟。

刚测试了另外一台摩托罗拉手机安卓13， 删除998条验证码短信，耗时10秒左右

可能是个例吧，我已经没有短信可以删除测试了。

**Comment by pz66** [comment]
真我GTneo6se， 安卓14，coloros 14，当时过滤出来删除，大概一万多条验证码短信，删除了5分钟都一直在转圈，重新打开软件后发现还剩几千条，又重新删，又消耗了比较长的时间，也删除了几分钟。

这是另外一台摩托罗拉安卓13手机，删除1000条验证码短信，耗时10秒，比较快。

真我手机已经没有短信可以测试了。下次短信比较多了我再试试

**Comment by davidche1116** [comment]
代码里是一条一条调用删除接口并等待完成的。我看这个之后有没有优化空间。如果部分手机系统删除接口本身就慢就没办法了。
